objects/nv_obj_Airport__c/nv_obj_Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nv_obj_Airport__c/fields/nv_fld_iataCode__c.field-meta.xml
<CustomField>
    <fullName>nv_fld_iataCode__c</fullName>
    <label>IATA Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/nv_obj_Airport__c/fields/nv_fld_latitude__c.field-meta.xml
<CustomField>
    <fullName>nv_fld_latitude__c</fullName>
    <label>Latitude</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/nv_obj_Airport__c/fields/nv_fld_longitude__c.field-meta.xml
<CustomField>
    <fullName>nv_fld_longitude__c</fullName>
    <label>Longitude</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/nv_obj_flight__c/nv_obj_flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FLT-{000}</displayFormat>
        <label>Flight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nv_obj_flight__c/fields/nv_fld_arrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>nv_fld_arrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Arrival airport from the flight</description>
    <label>Arrival Airport</label>
    <referenceTo>nv_obj_Airport__c</referenceTo>
    <relationshipLabel>Flights (Arrival Airport)</relationshipLabel>
    <relationshipName>ArrivalFlights</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/nv_obj_flight__c/fields/nv_fld_departureAirport__c.field-meta.xml
<CustomField>
    <fullName>nv_fld_departureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Departure airport from the flight</description>
    <label>Departure Airport</label>
    <referenceTo>nv_obj_Airport__c</referenceTo>
    <relationshipLabel>Flights (Departure Airport)</relationshipLabel>
    <relationshipName>DepartureFlights</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/nv_obj_flight__c/fields/nv_fld_flightDistance__c.field-meta.xml
<CustomField>
    <fullName>nv_fld_flightDistance__c</fullName>
    <description>Distance of the flight in Kilometers</description>
    <label>Flight Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

classes/NuvolarFlightsController_Test.cls
@isTest
private with sharing class NuvolarFlightsController_Test {
    @TestSetup
    private static void makeData(){
        List<nv_obj_Airport__c> airportList = new List<nv_obj_Airport__c>();
        nv_obj_Airport__c a1 = new nv_obj_Airport__c();
        a1.Name = 'Aeropuerto Internacional de la Región de Murcia';
        a1.nv_fld_iataCode__c = 'RMU';
        a1.nv_fld_latitude__c = 37.803;
        a1.nv_fld_longitude__c = -1.125;
        airportList.add(a1);

        nv_obj_Airport__c a2 = new nv_obj_Airport__c();
        a2.Name = 'Aeropuerto de Alicante-Elche';
        a2.nv_fld_iataCode__c = 'ALC';
        a2.nv_fld_latitude__c = 38.2822;
        a2.nv_fld_longitude__c = -0.558156;
        airportList.add(a2);

        insert airportList;

        List<nv_obj_flight__c> flightsList = new List<nv_obj_flight__c>();
        nv_obj_flight__c flight = new nv_obj_flight__c();
        flight.nv_fld_arrivalAirport__c = a1.Id;
        flight.nv_fld_departureAirport__c = a2.Id;
        flight.nv_fld_flightDistance__c = 72.82;
        flightsList.add(flight);

        insert flightsList;
    }

    @isTest
    private static void testGetAirportWithoutFilter(){
        Test.startTest();
        List<nv_obj_Airport__c> airportList = NuvolarFlightsController.getFilteredAirports(null);
        Test.stopTest();
        System.assertEquals(2, airportList.size(), 'Airport list have an incorrect size');
    }

    @isTest
    private static void testGetAirportWithFilter(){
        Test.startTest();
        List<nv_obj_Airport__c> airportList = NuvolarFlightsController.getFilteredAirports('RMU');
        Test.stopTest();
        System.assertEquals('RMU', airportList[0].nv_fld_iataCode__c, 'RMU airport not found');
    }

    @isTest
    private static void testGetAllFlights(){
        Test.startTest();
        List<nv_obj_flight__c> flightsList = NuvolarFlightsController.getAllFlights();
        Test.stopTest();
        System.assertEquals('RMU', flightsList[0].nv_fld_arrivalAirport__r.nv_fld_iataCode__c, 'Wrong arrival airport IATA Code');
        System.assertEquals('ALC', flightsList[0].nv_fld_departureAirport__r.nv_fld_iataCode__c, 'Wrong departure airport IATA Code');
    }

    @isTest
    private static void testSaveFlight(){
        Map<String, Object> arrAirport = new Map<String, Object>();
        Map<String, Object> deparAirport = new Map<String, Object>();
        Id arrAirportId = null;
        Id deparAirportId = null;
        
        Test.startTest();
        List<nv_obj_Airport__c> airportList = [SELECT Id, nv_fld_latitude__c, nv_fld_longitude__c,nv_fld_iataCode__c 
                                                FROM nv_obj_Airport__c
                                                WHERE nv_fld_iataCode__c IN ('RMU','ALC')];
        for (nv_obj_Airport__c airport : airportList){
            if (airport.nv_fld_iataCode__c == 'RMU'){
                arrAirport.put('id', airport.Id);
                arrAirportId = airport.Id;
                arrAirport.put('latitude', airport.nv_fld_latitude__c);
                arrAirport.put('longitude', airport.nv_fld_longitude__c);
            } else if (airport.nv_fld_iataCode__c == 'ALC'){
                deparAirport.put('id', airport.Id);
                deparAirportId = airport.Id;
                deparAirport.put('latitude', airport.nv_fld_latitude__c);
                deparAirport.put('longitude', airport.nv_fld_longitude__c);
            }
        }
        NuvolarFlightsController.saveFlight(arrAirport, deparAirport);

        nv_obj_flight__c newFlight = [SELECT Id,Name,nv_fld_flightDistance__c,nv_fld_departureAirport__c,nv_fld_arrivalAirport__c 
                                        FROM nv_obj_flight__c 
                                        WHERE nv_fld_arrivalAirport__c = :arrAirportId AND nv_fld_departureAirport__c = :deparAirportId
                                        LIMIT 1];
        Test.stopTest();
        System.assertEquals(72.82, newFlight.nv_fld_flightDistance__c, 'Distance incorrectly calculated');
    }
}